# Docker Compose setup for local development
# docker-compose.yml
version: '3.8'
services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: usmc_admin
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: usmc_portal
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: